FROM rocker/tidyverse:3.4.1

MAINTAINER "Paweł Zawistowski" dratewka@gmail.com

RUN R -e "install.packages(c('mlr', 'GGally', 'parallelMap'), repos='http://cran.rstudio.com/')"
RUN R -e "install.packages(c('xgboost','class'), repos='http://cran.rstudio.com/')"

    

